# Generated by Django 3.1.6 on 2021-06-02 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание')),
                ('width', models.FloatField(verbose_name='Ширина')),
                ('length', models.FloatField(verbose_name='Длина')),
                ('weight', models.FloatField(verbose_name='Вес')),
                ('where_from', models.CharField(max_length=200, verbose_name='Откуда')),
                ('where_to', models.CharField(max_length=200, verbose_name='Куда')),
                ('date', models.DateField(verbose_name='Когда')),
                ('time', models.TimeField(verbose_name='Во-сколько')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Груз',
                'verbose_name_plural': 'Грузы',
            },
        ),
    ]
