# Generated by Django 3.1.6 on 2021-06-14 12:13

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('phone_number', models.CharField(default='00000000000', max_length=50, null=True, verbose_name='Номер телефона')),
                ('rating', models.FloatField(default=5.0, verbose_name='Рейтинг')),
            ],
            options={
                'verbose_name': 'Мой пользователь',
                'verbose_name_plural': 'Мои пользователи',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='goods',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.myuser'),
        ),
    ]
