# Generated by Django 3.1.6 on 2021-06-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20210614_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='price',
            field=models.PositiveIntegerField(null=True, verbose_name='Цена'),
        ),
    ]
