# Generated by Django 3.1.6 on 2021-06-15 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_goods_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='height',
            field=models.FloatField(default=0.0, verbose_name='Высота'),
        ),
    ]
