# Generated by Django 3.1.6 on 2021-06-16 17:27

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0007_goods_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('image', models.ImageField(default=None, null=True, upload_to='images/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Картинка',
                'verbose_name_plural': 'Картинки',
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='prodile/', verbose_name='Изображение'),
        ),
        migrations.RemoveField(
            model_name='goods',
            name='image',
        ),
        migrations.AddField(
            model_name='goods',
            name='image',
            field=models.ManyToManyField(related_name='goods_images', to='goods.Image', verbose_name='Изображение'),
        ),
    ]
