# Generated by Django 3.1.6 on 2021-06-18 04:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goods', '0009_auto_20210618_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='goodser',
            field=models.BooleanField(default=False, verbose_name='Исполнитель'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='goodser',
            field=models.ManyToManyField(default=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL), related_name='goodser', to=settings.AUTH_USER_MODEL, verbose_name='Исполнители'),
        ),
    ]
